//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoskolaWebServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public Questions()
        {
            this.Answers = new HashSet<Answers>();
            this.Quizs = new HashSet<Quizs>();
        }
    
        public int ID { get; set; }
        public string QuestionText { get; set; }
        public string CorrectAnswer { get; set; }
        public byte[] Image { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedByUser { get; set; }
        public string ModifiedByUser { get; set; }
    
        public virtual ICollection<Answers> Answers { get; set; }
        public virtual ICollection<Quizs> Quizs { get; set; }
    }
}
