//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoskolaWebServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quizs
    {
        public Quizs()
        {
            this.Questions = new HashSet<Questions>();
        }
    
        public int ID { get; set; }
        public string QuizName { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public int Duration { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int QuizPoints { get; set; }
        public Nullable<int> ResultsID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedByUser { get; set; }
        public string ModifiedByUser { get; set; }
    
        public virtual Results Results { get; set; }
        public virtual ICollection<Questions> Questions { get; set; }
    }
}
